name: Publish to crates.io

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: read

jobs:
  publish:
    uses: qntx/workflows/.github/workflows/publish-crates.yml@v2
    permissions:
      contents: read
    with:
      packages: "xmtp xmtp-cli"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
