name: Publish to crates.io

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    uses: qntx/workflows/.github/workflows/publish-crates.yml@main
    with:
      packages: "xmtp xmtp-cli"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
